---
- hosts: all
  tasks:

     - name: create stack
       os_stack:
          name: "stack-wordpress"
          state: absent
       ignore_errors: True

     - pause:
          seconds: 20

     - name: GET TOKEN
       uri:
         url: "{{ iam_url }}/auth/tokens"
         method: POST
         body_format: raw
         follow_redirects: all
         status_code: 201
         return_content: yes
         validate_certs: yes
         HEADER_Content-Type: "application/json"
         body: "{{ lookup('template', 'files/token.json.j2',convert_data=True)|to_json }}"
       register: token

     - name: Delete RDS
       uri:
          url: "{{ rds_url }}/instances/{{ rds_id }}"
          method: DELETE
          body_format: json
          follow_redirects: all
          return_content: yes
          validate_certs: yes
          HEADER_Content-Type: "application/json"
          HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
          HEADER_X-Language: "en-us"
          body: '{ "keepLastManualBackup":"" }'
       register: rds
       ignore_errors: yes


     - debug:
            msg: "{{ rds }}"

     - pause:
          seconds: 20


     - name: Delete SUBNET
       uri:
            url: "{{ vpc_url }}/vpcs/{{ vpc_id }}/subnets/{{ subnet_id }}"
            method: DELETE
            body_format: raw
            follow_redirects: all
            return_content: yes
            validate_certs: yes
            status_code: 200,201,202,203,204
            HEADER_Content-Type: "application/json"
            HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
       register: subnet
       ignore_errors: yes

     - debug:
          msg: "{{ subnet }}"


     - pause:
           seconds: 20

     - name: Delete VPC
       uri:
           url: "{{ vpc_url }}/vpcs/{{ vpc_id }}"
           method: DELETE
           body_format: raw
           follow_redirects: all
           return_content: yes
           validate_certs: yes
           status_code: 200,201,202,203,204
           HEADER_Content-Type: "application/json"
           HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
       register: vpc
       ignore_errors: yes

     - debug:
           msg: "{{ vpc }}"


     - name: Delete Secgroup
       uri:
         url: "{{ vpc_url2 }}/security-groups/{{ secgroup_id }}"
         method: DELETE
         body_format: raw
         follow_redirects: all
         return_content: yes
         validate_certs: yes
         status_code: 200,201,202,203,204
         HEADER_Content-Type: "application/json"
         HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
       register: secgroup
       ignore_errors: yes


     - debug:
         msg: "{{ secgroup }}"

