heat_template_version: 2014-10-16

description: Template that creates a loadbalance server.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to enable SSH access to the instance.
  flavor:
    type: string
    description: Flavor to use for servers.
  network:
    type: string
    description: Network to attach server to.
  security_group:
    type: string
    description: Name of the security group to which the instances belongs to.
  elb_listener:
    type: string
    description: ID of the ELB listener the instance is attached to.
  db_host:
    type: string
    description: WordPress database host
  db_name:
     type: string
     description: WordPress database name
  db_root_password:
    type: string
    description: Root password for MySQL

resources:
  elb_member:
    type: OSE::ELB::Member
    properties:
      listener_id: { get_param: elb_listener }
      members:
        - server_id: { get_resource: nova_server }
          address: { get_attr: [nova_server, first_address] }

  elb_member2:
      type: OSE::ELB::Member
      properties:
        listener_id: { get_param: elb_listener }
        members:
          - server_id: { get_resource: nova_server2 }
            address: { get_attr: [nova_server2, first_address] }

  cloud_init:
     type: OS::Heat::CloudConfig
     properties:
       cloud_config:
           #cloud-config
           runcmd:
             - [ /home/cloud/mysql_conf.sh ,{ get_param: db_root_password },{ get_param: db_host },{ get_param: db_name } ]

  server_init:
    type: OS::Heat::MultipartMime
    properties:
        parts:
          - config: {get_resource: cloud_init}


  nova_server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: wordpress_test
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: network }
      availability_zone: eu-west-0a
      security_groups:
        - { get_param: security_group }
      user_data_format: RAW
      user_data:
          get_resource: server_init

  nova_server2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: wordpress_test
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: network }
      availability_zone: eu-west-0b
      security_groups:
        - { get_param: security_group }
      user_data_format: RAW
      user_data:
          get_resource: server_init